### ISSUE TITLE
Error when Auto loads the delta I trained.

### ISSUE THREAD

**Issue by DarkAlchy** [guaneec/custom-diffusion-webui#5] opened 2023-02-02 05:13 UTC
activating extra network delta with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000002816E906800>]: RuntimeError
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\stable-diffusion-webui\extensions\custom-diffusion-webui\cd_modules\extra_networks_deltas.py", line 38, in activate
    v[:] = v.detach() + d.to(model.device) * strength
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by guaneec** [comment] 2023-02-02 05:21
Can you provide your command line arguments?
Just pushed the fix; try updating.

**Comment by DarkAlchy** [comment] 2023-02-02 05:50
Huh?  Automatic1111 prompt you mean?

**Comment by guaneec** [comment] 2023-02-02 05:54
How you launched the program, like did you add anything like "--medvram"?
Anyways, try updating the extension again. Probably works now.

**Comment by DarkAlchy** [comment] 2023-02-02 06:00
I did update and now Auto's box you click to load lora, delta, hypernetwork, etc... delta went POOF.  I restarted auto, closed it all and restarted and gone.  I removed the extension and redownloaded it but no dice.

**Comment by DarkAlchy** [comment] 2023-02-02 06:01
patched in extra network: deltas it said in the cli.

Gone post update/fix
![image](https://user-images.githubusercontent.com/10561690/216244219-d1c621b4-0feb-41fd-a03b-9feb051399c6.png)

I then added it by hand and

activating extra network delta with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000002C01C58D750>]: KeyError
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\stable-diffusion-webui\extensions\custom-diffusion-webui\cd_modules\extra_networks_deltas.py", line 23, in activate
    st = safe_open(deltas.deltas[delta_name], 'pt')
KeyError: 'Drac0-400'

**Comment by guaneec** [comment] 2023-02-02 06:10
I can't reproduce this.
Can you paste the whole cli log after you started the web ui?
I'm looking for some other error when the extension is loaded.

**Comment by DarkAlchy** [comment] 2023-02-02 06:16
Yes, here ya go:

venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 226d840e84c5f306350b0681945989b86760e616
Installing requirements for Web UI

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Dreambooth revision: 21ddebabb47274255d516e655f997d9ddadc0fe4
SD-WebUI revision: 226d840e84c5f306350b0681945989b86760e616

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.16rc425 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.

#######################################################################################################

Launching Web UI with arguments: --theme dark --medvram --xformers --disable-safe-unpickle --port 9000 --api --opt-channelslast
SD-Webui API layer loaded
Loading weights [a153f10aa4] from D:\stable-diffusion-webui\models\Stable-diffusion\2.x_models\v2-1_768-ema-pruned-pruned.ckpt
Creating model from config: D:\stable-diffusion-webui\models\Stable-diffusion\2.x_models\v2-1_768-ema-pruned-pruned.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Model loaded in 4.9s (load weights from disk: 1.2s, create model: 0.3s, apply weights to model: 0.7s, apply channels_last: 0.6s, apply half(): 0.7s, move model to device: 0.3s, load textual inversion embeddings: 1.2s).
patched in extra network ui page: deltas
patched in extra network: deltas
Running on local URL:  http://127.0.0.1:9000

To create a public link, set `share=True` in `launch()`.

**Comment by guaneec** [comment] 2023-02-02 06:25
Did you fully restart the web ui cli, not just clicking reload UI?
Reloading the UI eats the delta tab, I don't know why yet.

**Comment by DarkAlchy** [comment] 2023-02-02 06:26
> Did you fully restart the web ui cli, not just clicking reload UI? Reloading the UI eats the delta tab, I don't know why yet.

Yep, and when you asked I clicked the X and fired it back up just for you.

**Comment by DarkAlchy** [comment] 2023-02-02 06:32
The error is gone.  btw, as to your missing tab issue I had to f5 to get his button to work at all and in the cli was this error message: Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

**Closed as completed** 2023-02-02 06:38 UTC
